### PR TITLE
Add wyrand (upadted wyhash variant)

### PR DESCRIPTION
**Pull request by palimondo**
Resolves issue #16.

As discussed in lemire/SwiftWyhash/issues/6

I *hope* this works 🤞, because I have just cloned every `wyhash`/`wyhash64` occurrence into `wyrand`…

### CODE REVIEW

**Comment by lemire** [comment]
I'm taking it out for a spin.

**Comment by lemire** [comment]
Made a few fixes but it was fine.

**Comment by flyingmutant** [comment]
@lemire , are results of your wyrand testing publicly available?

**Comment by lemire** [comment]
@flyingmutant Folks should be able to run my tests.

The exact results depend on many factors, so I prefer to just offer code that people can run rather than constantly update the numbers for different platforms.

**Comment by lemire** [comment]
See our summary at https://github.com/lemire/testingRNG#visual-summary

**Comment by flyingmutant** [comment]
Thanks, I'll try to run the tests myself. I was asking because README only mentions wyhash, not wyrand.

**Comment by lemire** [comment]
Please refer to the title of the issue: 'Add wyrand (updated wyhash variant)'

**Comment by lemire** [comment]
Specifically, they are variations.

There must be at least 7 different wyhash/wyrng variations out there... and about ~30 PCG variations and so forth. For the purpose of the README, we pick a representative of each.

Of course, pull requests are invited.

**Comment by flyingmutant** [comment]
I don't know if it is fair to refer to them as "variations" -- one is doing 2x more work (specifically, bit mixing) than the other, and it is reasonable to expect that this can affect statistical quality.

**Comment by lemire** [comment]
@flyingmutant Fair point but consider that wyhash and wyrng is not 'one thing' but a family of functions that far exceeds what is present here.

**Pull request merged**
